# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
