# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 10:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20170723_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to=b'filer.Image'),
        ),
    ]
